---
title: "CO₂ Emisyon Oranı Ve Ülkelerin Ekonomik Büyümüşlüğü"
author: 
  - Şeyma Fidan[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080462

# Vize Hakkında Önemli Bilgiler

**Proje önerisi gönderimi, ekampus sistemine bir zip dosyası yüklenerek yapılacaktır. Sisteme zip dosyası yüklemezseniz ara sınav ve final sınavlarına girmemiş sayılırsınız.**

**Proje klasörünüzü sıkıştırdıktan sonra (`ÖğrenciNo.zip` dosyası) 28 Nisan 2024 23:59'a kadar *ekampus.ankara.edu.tr* adresine yüklemeniz gerekmektedir.**

\colorbox{WildStrawberry}{Daha fazla bilgi için proje klasöründeki README.md dosyasını okuyunuz.}

# Giriş
  Ülkeler ekonomik gelişmelerini planlamak zorundadır . Bu gelişmeler ise uzun , kısa ve orta vadede olabilir . Az gelişmiş ve gelişmekte olan ülkeler için ekonomik büyüme çok önemlidir .Ekonomik olarak büyüyünce kalkınmış bir ülke olabileceklerini düşüyorlar . Tabi ülkeler ön plana ekonomik büyüme arzusunu alınca , dünya genelinde enerji tüketimini artırırken, söz konusu enerji için birincil enerji kaynağı olan fosil yakıt tüketimini arttırmaktadırlar . Doğal olarak fosil yakıt tüketimi de CO2 salınımını arttırmıştır . Küresel ısınma sorunu açığa çıktıkça ; ülkeler , otoriteler ve bilim insanları bu konuda çalışmalar yapmaya başlamışlardır . ‘’ Birleşmiş Milletler (BM) tarafından Ekim 2015’te yayımlanan, “İklim Bağlantılı Doğal Afetlerin İnsani Maliyeti” isimli raporda, 20 yılda kayıtlara geçen küresel olarak toplam 6,457 doğal afetin %90’ı sel, fırtına, sıcak hava dalgası, kuraklık ve diğer aşırı iklim hareketlerinden kaynaklandığı; 1995 yılından bu yana aşırı iklim hareketleri kaynaklı afetler nedeniyle 606 bin kişinin yaşamını yitirdiği, 4,1 milyar insanın ise etkilendiği belirtilmektedir’’* Sera gazı salınımının azaltılması için ekonomik göstergeler ile enerji tüketimi ve CO2 emisyonu arasındaki ilişkinin belirlenmesi gerekir. Ülkeler çalışmalarına üst gelir grubu ülkeleri tercih etmiştir ve çoğunlukla onları kendi aralarında karşılaştırmıştır . Bu analizde ise ayrım gözetilmeksizin gelişmiş , geri kalmış vb. tüm ülkeler hakkında bilgi edineceğiz . 


* Sel, A., & Göktolga, Z. G. (2020). 11. Kalkınma Planı Çerçevesinde Sektörel CO2 Salımı Değerleri Projeksiyonu. Akdeniz İİBF Dergisi, 20(2),sayfa 159


## Çalışmanın Amacı
Endüstriye ve ülkeye göre çıktı birimi başına CO₂ doğrudan ve dolaylı emisyonları  görünmektedir . Ülkeleri endüstrilerine göre ayıracağım . En fazla hangi endüstrilerde çıktı birimi başına CO₂ olduğunu bulacağım ve bu oranla ülkenin kalkınmışlığı arasında bir bağ var mı bakacağım.  


## Literatür 
 Literatür taraması yapıldığında karbon salımının incelendiği çalışmalara fazlasıyla rastlanmıştır.Elbette ilgilenilen ülkelerle veriler arasında farklar olduğu gibi analiz sonuçları da birbirinden farklı olmuştur . Bu analizi diğer analizlerden ayıran en büyük fark tüm ülkeleri de kapsayacağıdır . 
  Çalışmada, CO2 emisyon düzeyi ile ülkelerin diğer ülkelere yaptıkları yabancı 
sermaye yatırımı düzeyi arasındaki ilişki, 12 üst gelir grubuna dahil ülkenin 1970-
2012 yılları arasındaki verileri kullanılarak, Genelleştirilmiş Momentler Metodunun 
(GMM) sistem yöntemi ile analiz edilmiştir. Çalışmada yardımcı açıklayıcı değişkenler olarak kişi başına düşen enerji tüketimi ve kişi başına düşen gelir kullanılmıştır.@article{Akın, C. S. (2014)
  Ekonominin tamamını ilgilendiren analizlerde girdi çıktı tabloları etkin olarak kullanılabilir. Girdi çıktı modelleri ilk olarak Amerikan ekonomisinin yapısal analizinde W.W. Leontief tarafından 1930 yılında incelenmiştir. Girdi çıktı analizinde bir bölgede yer alan sektörlerin birbirleriyle olan ilişkilerini inceler. Herhangi bir mali yılda sektörlerin aramal kullanımlarını ve miktarını para birimi cinsinden verir. 
Özellikle bir ülkede sektörel olarak GSYH’nın dağılımı bu tablolar ile rahatlıkla görülebilir.@article{Sel, A., & Göktolga, Z. G. (2020),
  This research pretends to contribute to the existing empirical literature. At first we revisit the link between renewable and non-renewable energy and economic growth. The correlation between carbon dioxide emissions and growth, as well as, globalization and economic growth was analyzed. The econometric model is formulated based on the assumptions presented in the literature review. This study presents important findings for the Portuguese economy; these can be used by policy makers.@article{Leitão, N. C. (2014)
  Therefore, this study aims to answer these two questions:
1) What is the level of CO2 emission produced by the global construction sector?
2) What are the hot spots and improvement opportunities of the global construction sector?
In order to answer these two questions, this study conducts inputoutput analysis based the world input-output table in 2009.2 The study considers 40 countries and 26 kinds of energy. It analyses the CO2 emission produced by energy use and non-energy use for the global
construction sector.@article{Lizhen H.(2018)


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>

